# For only Running Post-services and PostsDB (Postgres)

version: '3.8'

services:

  app:
    container_name: user-services-app
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

    # For Development use only
    command: sh -c "npm install && npm run dev" #This overrided Dockerfile CMD
    volumes:
      - .:/app

  mongodb:
    container_name: user-services-db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - user-mongodb-data:/data/db

volumes:
  user-mongodb-data: