# For only Running USER Database (MongoDB)

version: '3.8'

services:

  mongodb:
    container_name: user-services-db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - user-mongodb-data:/data/db

volumes:
  user-mongodb-data: