# For Testing Database

version: '3.8'

services:

# Reference : https://www.youtube.com/watch?v=vm3YfOHf_Cc
  app:
    container_name: user-services-app
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - CONNECTION_URL=mongodb://user-services-db:27017/ # either 'mongodb' or container name (user-services-db)
      - PORT=5000

  mongodb:
    container_name: user-services-db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: {}