# For Testing Database

version: '3.8'

services:

# Reference : https://www.youtube.com/watch?v=vm3YfOHf_Cc
  app:
    container_name: user-services-app
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  mongodb:
    container_name: user-services-db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: {}