# For only Running POST Database (Postgres)

version: '3.8'

services:
  app:
    container_name: post-services-app
    build: .
    ports:
      - 8000:8000
    depends_on:
      - postgres

    # For Development use only
    volumes:
      - .:/app

  postgres:
    container_name: post-services-db
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=room-db   #Database's Name
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data


volumes:
  db:
    driver: local