# For only Running POST Database (Postgres)

version: '3.8'

services:

  postgres:
    container_name: post-services-db
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=room-db   #Database's Name
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data


volumes:
  db:
    driver: local